<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Patient;

class PatientSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $patients = [
            [
                'uhid' => 'UHID001',
                'name' => 'John Smith',
                'dob' => '1985-03-15',
                'gender' => 'Male',
                'phone' => '+1-555-0101',
                'email' => 'john.smith@example.com',
                'address' => '123 Main Street, New York, NY 10001',
                'blood_group' => 'O+',
                'guardian_name' => 'Mary Smith',
                'guardian_phone' => '+1-555-0199',
            ],
            [
                'uhid' => 'UHID002',
                'name' => 'Emily Johnson',
                'dob' => '1990-07-22',
                'gender' => 'Female',
                'phone' => '+1-555-0102',
                'email' => 'emily.johnson@example.com',
                'address' => '456 Oak Avenue, Los Angeles, CA 90001',
                'blood_group' => 'A+',
                'guardian_name' => 'Robert Johnson',
                'guardian_phone' => '+1-555-0198',
            ],
            [
                'uhid' => 'UHID003',
                'name' => 'Michael Chen',
                'dob' => '1978-11-08',
                'gender' => 'Male',
                'phone' => '+1-555-0103',
                'email' => 'michael.chen@example.com',
                'address' => '789 Pine Road, Chicago, IL 60601',
                'blood_group' => 'B+',
                'guardian_name' => 'Lisa Chen',
                'guardian_phone' => '+1-555-0197',
            ],
            [
                'uhid' => 'UHID004',
                'name' => 'Sarah Williams',
                'dob' => '1995-05-30',
                'gender' => 'Female',
                'phone' => '+1-555-0104',
                'email' => 'sarah.williams@example.com',
                'address' => '321 Elm Street, Houston, TX 77001',
                'blood_group' => 'AB+',
                'guardian_name' => 'James Williams',
                'guardian_phone' => '+1-555-0196',
            ],
            [
                'uhid' => 'UHID005',
                'name' => 'David Brown',
                'dob' => '1982-09-12',
                'gender' => 'Male',
                'phone' => '+1-555-0105',
                'email' => 'david.brown@example.com',
                'address' => '654 Maple Drive, Phoenix, AZ 85001',
                'blood_group' => 'O-',
                'guardian_name' => 'Patricia Brown',
                'guardian_phone' => '+1-555-0195',
            ],
            [
                'uhid' => 'UHID006',
                'name' => 'Jessica Davis',
                'dob' => '1988-12-04',
                'gender' => 'Female',
                'phone' => '+1-555-0106',
                'email' => 'jessica.davis@example.com',
                'address' => '987 Cedar Lane, Philadelphia, PA 19101',
                'blood_group' => 'A-',
                'guardian_name' => 'Mark Davis',
                'guardian_phone' => '+1-555-0194',
            ],
            [
                'uhid' => 'UHID007',
                'name' => 'Robert Wilson',
                'dob' => '1965-02-18',
                'gender' => 'Male',
                'phone' => '+1-555-0107',
                'email' => 'robert.wilson@example.com',
                'address' => '147 Birch Court, San Antonio, TX 78201',
                'blood_group' => 'B-',
                'guardian_name' => 'Helen Wilson',
                'guardian_phone' => '+1-555-0193',
            ],
            [
                'uhid' => 'UHID008',
                'name' => 'Amanda Taylor',
                'dob' => '1992-06-25',
                'gender' => 'Female',
                'phone' => '+1-555-0108',
                'email' => 'amanda.taylor@example.com',
                'address' => '258 Walnut Street, San Diego, CA 92101',
                'blood_group' => 'AB-',
                'guardian_name' => 'George Taylor',
                'guardian_phone' => '+1-555-0192',
            ],
            [
                'uhid' => 'UHID009',
                'name' => 'James Anderson',
                'dob' => '1973-10-14',
                'gender' => 'Male',
                'phone' => '+1-555-0109',
                'email' => 'james.anderson@example.com',
                'address' => '369 Ash Boulevard, Dallas, TX 75201',
                'blood_group' => 'O+',
                'guardian_name' => 'Karen Anderson',
                'guardian_phone' => '+1-555-0191',
            ],
            [
                'uhid' => 'UHID010',
                'name' => 'Sophia Thomas',
                'dob' => '2001-04-09',
                'gender' => 'Female',
                'phone' => '+1-555-0110',
                'email' => 'sophia.thomas@example.com',
                'address' => '741 Spruce Way, San Jose, CA 95101',
                'blood_group' => 'A+',
                'guardian_name' => 'Thomas Thomas',
                'guardian_phone' => '+1-555-0190',
            ],
            [
                'uhid' => 'UHID011',
                'name' => 'Daniel Jackson',
                'dob' => '1989-08-31',
                'gender' => 'Male',
                'phone' => '+1-555-0111',
                'email' => 'daniel.jackson@example.com',
                'address' => '852 Chestnut Drive, Austin, TX 78701',
                'blood_group' => 'B+',
                'guardian_name' => 'Nancy Jackson',
                'guardian_phone' => '+1-555-0189',
            ],
            [
                'uhid' => 'UHID012',
                'name' => 'Olivia White',
                'dob' => '1997-01-19',
                'gender' => 'Female',
                'phone' => '+1-555-0112',
                'email' => 'olivia.white@example.com',
                'address' => '963 Cypress Place, Jacksonville, FL 32201',
                'blood_group' => 'O+',
                'guardian_name' => 'Edward White',
                'guardian_phone' => '+1-555-0188',
            ],
            [
                'uhid' => 'UHID013',
                'name' => 'William Harris',
                'dob' => '1960-11-23',
                'gender' => 'Male',
                'phone' => '+1-555-0113',
                'email' => 'william.harris@example.com',
                'address' => '159 Magnolia Street, Fort Worth, TX 76101',
                'blood_group' => 'AB+',
                'guardian_name' => 'Barbara Harris',
                'guardian_phone' => '+1-555-0187',
            ],
            [
                'uhid' => 'UHID014',
                'name' => 'Charlotte Martin',
                'dob' => '1994-09-05',
                'gender' => 'Female',
                'phone' => '+1-555-0114',
                'email' => 'charlotte.martin@example.com',
                'address' => '357 Poplar Avenue, Columbus, OH 43201',
                'blood_group' => 'A-',
                'guardian_name' => 'Charles Martin',
                'guardian_phone' => '+1-555-0186',
            ],
            [
                'uhid' => 'UHID015',
                'name' => 'Benjamin Thompson',
                'dob' => '1981-07-17',
                'gender' => 'Male',
                'phone' => '+1-555-0115',
                'email' => 'benjamin.thompson@example.com',
                'address' => '468 Redwood Circle, Charlotte, NC 28201',
                'blood_group' => 'O-',
                'guardian_name' => 'Susan Thompson',
                'guardian_phone' => '+1-555-0185',
            ],
        ];

        foreach ($patients as $patientData) {
            Patient::updateOrCreate(['uhid' => $patientData['uhid']], $patientData);
        }

        $this->command->info(count($patients) . ' patients seeded successfully!');
    }
}
